"""Initial migration.

Revision ID: 97ed9f05c02a
Revises: 
Create Date: 2024-06-15 19:08:51.373859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ed9f05c02a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('userType', sa.String(length=20), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('fs_uniquifier', name=op.f('uq_user_fs_uniquifier')),
    sa.UniqueConstraint('id', name=op.f('uq_user_id'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('place', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venue'))
    )
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_timestamp'), ['timestamp'], unique=False)

    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('timing', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name=op.f('fk_show_venue_id_venue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_show'))
    )
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_show_timestamp'), ['timestamp'], unique=False)

    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('showTime', sa.String(length=255), nullable=False),
    sa.Column('sheats', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], name=op.f('fk_booking_show_id_show')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_booking_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking'))
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_timestamp'), ['timestamp'], unique=False)

    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], name=op.f('fk_image_show_id_show')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_timestamp'))

    op.drop_table('booking')
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_show_timestamp'))

    op.drop_table('show')
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_timestamp'))

    op.drop_table('venue')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
